In [3]:
import numpy as np

## DataTypes & Attributes 

In [2]:
#Numpy's main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1,2.0,3.3],[4,5,6.5]])
a3 = np.array([[[1,2,3],[4,5,6,],[4,5,7]]])

In [5]:
a2


array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [4, 5, 7]]])

In [7]:
a1.shape

(3,)

In [8]:
a1.ndim , a2.ndim, a3.ndim

(1, 2, 3)

In [9]:
 import pandas as pd

In [10]:
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## Creating Arrays

In [11]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [14]:
ones = np.ones()

TypeError: ones() missing 1 required positional argument: 'shape'

In [13]:
type(ones)

NameError: name 'ones' is not defined

In [15]:
range_array = np.arange(0,10,2)

In [16]:
range_array

array([0, 2, 4, 6, 8])

In [6]:
  random_array_3 = np.random.rand(5, 3)
  random_array_3

array([[0.99405348, 0.82551305, 0.62745641],
       [0.97065327, 0.69144409, 0.79828159],
       [0.07333198, 0.02251764, 0.70982583],
       [0.92426219, 0.32350795, 0.72049071],
       [0.56062916, 0.99731825, 0.75557471]])

In [7]:
##np.rabom.seed()
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[0, 8, 3],
       [2, 2, 6],
       [5, 2, 1],
       [3, 1, 5],
       [1, 9, 4]])

In [8]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [10]:
ones = np.ones(3)
ones

array([1., 1., 1.])

# 

# 

In [11]:
a1 + ones

array([2., 3., 4.])

In [12]:
a1 - ones

array([0., 1., 2.])

In [16]:
massive_array[:10]

array([0.46161975, 0.28235376, 0.48177776, 0.34235368, 0.54563131,
       0.86602312, 0.71190076, 0.98505548, 0.70952361, 0.89208358])

In [15]:
massive_array = np.random.random(100000)
massive_array.size

100000

In [18]:
%timeit sum(massive_array) #Python's Sum()
%timeit np.sum(massive_array)

19.4 ms ± 719 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
55.3 µs ± 2.98 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
