In [1]:
import numpy as np

In [2]:
a1=np.array((1,2,3))

In [3]:
a1

array([1, 2, 3])

In [5]:
a1.shape

(3,)

In [6]:
a1.reshape(3,1)

array([[1],
       [2],
       [3]])

In [7]:
a2_reshape = np.random.random(10)
a2_reshape

array([0.64160587, 0.88972356, 0.2319927 , 0.62196292, 0.28052916,
       0.48130253, 0.26167492, 0.83002612, 0.35003799, 0.12297833])

In [14]:
a= a2_reshape.reshape(10,1)

In [15]:
a

array([[0.64160587],
       [0.88972356],
       [0.2319927 ],
       [0.62196292],
       [0.28052916],
       [0.48130253],
       [0.26167492],
       [0.83002612],
       [0.35003799],
       [0.12297833]])

In [16]:
a * a1

array([[0.64160587, 1.28321175, 1.92481762],
       [0.88972356, 1.77944713, 2.66917069],
       [0.2319927 , 0.4639854 , 0.6959781 ],
       [0.62196292, 1.24392584, 1.86588875],
       [0.28052916, 0.56105832, 0.84158748],
       [0.48130253, 0.96260505, 1.44390758],
       [0.26167492, 0.52334983, 0.78502475],
       [0.83002612, 1.66005223, 2.49007835],
       [0.35003799, 0.70007598, 1.05011396],
       [0.12297833, 0.24595665, 0.36893498]])

In [17]:
a.T

array([[0.64160587, 0.88972356, 0.2319927 , 0.62196292, 0.28052916,
        0.48130253, 0.26167492, 0.83002612, 0.35003799, 0.12297833]])

In [18]:
a.shape

(10, 1)

In [19]:
a.T

array([[0.64160587, 0.88972356, 0.2319927 , 0.62196292, 0.28052916,
        0.48130253, 0.26167492, 0.83002612, 0.35003799, 0.12297833]])

In [20]:
a.T.shape

(1, 10)

In [22]:
a.T

array([[0.64160587, 0.88972356, 0.2319927 , 0.62196292, 0.28052916,
        0.48130253, 0.26167492, 0.83002612, 0.35003799, 0.12297833]])

Dot Product

In [35]:
np.random.seed(0)
mat1 = np.random.randint(10,size=(5,3))
mat2 = np.random.randint(10,size=(5,3))


In [36]:
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [37]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [38]:
#Hadamard Product
mat1 * mat2
    

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [39]:
mat=mat1.T

In [34]:
mat1=mat1.T.shape

AttributeError: 'tuple' object has no attribute 'T'

In [41]:
mat3 = np.dot(mat,mat2)

mat3

In [42]:
mat3

array([[121, 114,  77],
       [153, 108,  80],
       [135,  69,  84]])