In [1]:
import numpy as np

In [2]:
#1 D Array
a = np.array([1,2,3])

In [3]:
a.shape

(3,)

In [4]:
b = np.array([(1,2,3),(4,5,6)])

In [5]:
b.shape

(2, 3)

In [6]:
c = np.random.rand(8,8)

In [7]:
c.shape

(8, 8)

In [8]:
c.size

64

In [19]:
d = c.reshape(64,)

In [20]:
print(d.shape)
print(d)

(64,)
[4.26029732e-01 9.33376205e-01 9.05522890e-01 2.24156891e-02
 8.56701401e-01 4.92806753e-01 1.98950435e-05 6.23201163e-01
 9.62028557e-01 9.88669659e-01 9.44654380e-01 6.53955216e-01
 1.71149993e-01 3.89312115e-02 9.29615361e-01 6.93713009e-01
 3.25262394e-01 4.46077564e-01 3.85934388e-01 8.85943233e-01
 3.86384001e-01 9.17065211e-01 1.64173443e-01 5.73943867e-01
 4.46597217e-01 8.04640363e-01 6.82137344e-01 2.46539156e-01
 3.28321429e-01 1.65478002e-01 9.46225814e-02 1.10624295e-01
 5.81844431e-01 3.93315617e-04 5.44825622e-01 8.95888892e-01
 4.03833926e-01 9.08287712e-01 1.40383326e-01 8.07561265e-01
 4.14268177e-01 6.96975894e-01 7.08642789e-01 1.78823922e-01
 5.02758986e-01 5.60170930e-01 5.78775501e-01 3.59896571e-01
 1.23832162e-01 4.34667024e-01 4.64043779e-01 6.80535726e-01
 5.34831903e-01 1.93929495e-01 5.46348519e-01 7.70505815e-01
 9.36710218e-02 1.91981247e-01 8.69343719e-01 6.40952665e-02
 8.23150014e-01 2.80305211e-01 8.34553960e-01 7.89230550e-01]


In [21]:
d.dtype

dtype('float64')

In [22]:
np.zeros(1)

array([0.])

In [23]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
np.random.randn(8,8)

array([[-0.94382968,  1.14485634,  1.55229213,  1.51848561, -0.20676135,
        -0.0890137 ,  0.2363807 ,  0.19549253],
       [ 1.46283391,  1.02933212,  0.49604312,  1.20621904, -0.21774499,
         1.43778317,  0.45987762,  1.01000403],
       [ 0.58055479, -1.05212759,  0.14465699, -2.43701556,  1.07747571,
         2.54290546, -0.86016428,  1.89427859],
       [-0.12220099, -1.01895651,  0.23264885, -1.05170449, -0.84902809,
        -0.86320302,  1.56824601,  0.89371531],
       [ 0.00317864, -0.9315526 , -0.21827136, -1.33689916, -0.41691419,
         2.34925134,  0.52549211,  0.58713108],
       [-0.91732492,  0.87311563,  0.84790252,  1.65560307,  0.47659539,
        -0.01771053,  1.32907793,  0.94325174],
       [ 0.80407376,  1.11612676,  0.23099167,  1.61549653, -1.40084393,
        -0.14072485, -0.64503246, -0.3069017 ],
       [-0.29924263,  0.00396431,  1.01460436,  0.50008922, -0.21883701,
        -0.95443989, -1.07881192,  0.35046011]])

In [24]:
e = np.random.randint(40, size=(8,8))

In [25]:
e

array([[28, 27,  6, 34, 23, 15,  9, 11],
       [ 6, 17,  5, 32,  3,  2,  0, 13],
       [37, 25, 21, 35,  8,  4, 18, 22],
       [ 4, 16,  7, 37,  3, 25, 20,  1],
       [31,  4,  5,  1, 33, 26, 15, 36],
       [ 1, 27, 12, 29, 38,  9, 34, 38],
       [15, 24, 36, 25, 13, 30, 30,  0],
       [32, 30,  9, 31, 31, 10, 16, 27]])

In [26]:
e.shape

(8, 8)

In [33]:
f = e.reshape(64)

In [34]:
f.shape

(64,)

In [27]:
e.T  #Transpose of the matrix

array([[28,  6, 37,  4, 31,  1, 15, 32],
       [27, 17, 25, 16,  4, 27, 24, 30],
       [ 6,  5, 21,  7,  5, 12, 36,  9],
       [34, 32, 35, 37,  1, 29, 25, 31],
       [23,  3,  8,  3, 33, 38, 13, 31],
       [15,  2,  4, 25, 26,  9, 30, 10],
       [ 9,  0, 18, 20, 15, 34, 30, 16],
       [11, 13, 22,  1, 36, 38,  0, 27]])

In [38]:
f = f.reshape(4,4,4)

In [35]:
f.shape

(4, 4, 4)

In [36]:
f

array([[[26, 35, 19,  7],
        [38,  1,  7, 27],
        [29, 26, 29, 28],
        [25,  6, 10, 11]],

       [[37, 13, 29, 15],
        [11, 21,  8, 10],
        [25, 39,  2,  8],
        [37, 26, 23,  5]],

       [[38, 16, 15, 11],
        [39, 29, 22,  7],
        [ 2, 22,  4,  7],
        [ 7, 23, 20, 24]],

       [[ 5, 13, 23, 22],
        [ 2, 22,  9,  6],
        [38, 34, 16, 10],
        [11,  3,  6, 38]]])

In [33]:
g = np.random.randint(16, size=(8,8))

In [34]:
g.shape
print(g)

[[ 6  1  5  9  5  6 12 10]
 [ 9 14  2  0 15 10  2 15]
 [13 13 12 15 12  8 13  7]
 [10  2 11  7  7  0 14 15]
 [11  3  1  3 15  0  6 11]
 [ 0  5  3  9  6  0 13 13]
 [10  7 12  8  2  3  6  2]
 [ 5  2 13  7  3  9  5 14]]


In [35]:
g.resize(10,10)

In [36]:
g.shape

(10, 10)

In [37]:
g

array([[ 6,  1,  5,  9,  5,  6, 12, 10,  9, 14],
       [ 2,  0, 15, 10,  2, 15, 13, 13, 12, 15],
       [12,  8, 13,  7, 10,  2, 11,  7,  7,  0],
       [14, 15, 11,  3,  1,  3, 15,  0,  6, 11],
       [ 0,  5,  3,  9,  6,  0, 13, 13, 10,  7],
       [12,  8,  2,  3,  6,  2,  5,  2, 13,  7],
       [ 3,  9,  5, 14,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

In [46]:
g.resize(4,4)

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [38]:
g[5]

array([12,  8,  2,  3,  6,  2,  5,  2, 13,  7])

In [39]:
g[3,2] = 30

In [55]:
g

array([[ 1,  9,  9, 15,  9,  0, 12, 14],
       [ 1,  2,  5,  5, 12,  3,  5,  8],
       [10,  3, 14,  8,  5, 13,  5,  6],
       [11,  4, 30, 12,  1,  4,  3, 15],
       [ 7, 14, 15,  4,  0,  1, 15,  0],
       [ 9,  1,  1,  1, 15, 12,  2,  5],
       [13, 13, 10, 14,  9,  6,  6,  9],
       [ 7,  1,  8,  1, 14, 10, 14,  3]])

In [40]:
g[1:4,4]

array([ 2, 10,  1])

In [60]:
e.shape

(8, 8)

In [41]:
#Scalar Math
np.add(g,100)

array([[106, 101, 105, 109, 105, 106, 112, 110, 109, 114],
       [102, 100, 115, 110, 102, 115, 113, 113, 112, 115],
       [112, 108, 113, 107, 110, 102, 111, 107, 107, 100],
       [114, 115, 130, 103, 101, 103, 115, 100, 106, 111],
       [100, 105, 103, 109, 106, 100, 113, 113, 110, 107],
       [112, 108, 102, 103, 106, 102, 105, 102, 113, 107],
       [103, 109, 105, 114, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100]])

In [62]:
np.subtract(g,100)

array([[ -97, -100,  -89,  -92,  -89,  -97,  -88,  -85],
       [ -92,  -88,  -94,  -94,  -94,  -86,  -91,  -85],
       [ -86,  -88,  -96,  -97,  -86,  -85,  -99,  -88],
       [ -90,  -99,  -70,  -90, -100,  -96,  -88,  -96],
       [ -96,  -95,  -96,  -97,  -89,  -99,  -94,  -90],
       [ -91,  -85,  -96,  -91,  -86,  -85,  -90,  -92],
       [ -95,  -93,  -90,  -89,  -93,  -95,  -91,  -90],
       [ -86, -100,  -91,  -93,  -85,  -93,  -99,  -91]])

In [63]:
np.multiply(g,100)

array([[ 300,    0, 1100,  800, 1100,  300, 1200, 1500],
       [ 800, 1200,  600,  600,  600, 1400,  900, 1500],
       [1400, 1200,  400,  300, 1400, 1500,  100, 1200],
       [1000,  100, 3000, 1000,    0,  400, 1200,  400],
       [ 400,  500,  400,  300, 1100,  100,  600, 1000],
       [ 900, 1500,  400,  900, 1400, 1500, 1000,  800],
       [ 500,  700, 1000, 1100,  700,  500,  900, 1000],
       [1400,    0,  900,  700, 1500,  700,  100,  900]])

In [64]:
np.power(g,2)

array([[  9,   0, 121,  64, 121,   9, 144, 225],
       [ 64, 144,  36,  36,  36, 196,  81, 225],
       [196, 144,  16,   9, 196, 225,   1, 144],
       [100,   1, 900, 100,   0,  16, 144,  16],
       [ 16,  25,  16,   9, 121,   1,  36, 100],
       [ 81, 225,  16,  81, 196, 225, 100,  64],
       [ 25,  49, 100, 121,  49,  25,  81, 100],
       [196,   0,  81,  49, 225,  49,   1,  81]])

In [65]:
#Vector Math
np.add(g,e)

array([[29, 35, 30, 15, 49,  4, 19, 42],
       [37, 38, 35, 34, 31, 20, 19, 26],
       [51, 25, 33, 18, 25, 36,  9, 22],
       [35, 40, 32, 18, 37, 30, 35,  9],
       [42, 21, 19, 14, 50, 30, 28, 17],
       [11, 37,  8, 16, 21, 38, 30, 32],
       [10, 20, 33, 33,  9, 27, 18, 16],
       [52, 34, 25, 17, 26, 10,  7, 47]])

In [67]:
np.multiply(g,e)

array([[ 78,   0, 209,  56, 418,   3,  84, 405],
       [232, 312, 174, 168, 150,  84,  90, 165],
       [518, 156, 116,  45, 154, 315,   8, 120],
       [250,  39,  60,  80,   0, 104, 276,  20],
       [152,  80,  60,  33, 429,  29, 132,  70],
       [ 18, 330,  16,  63,  98, 345, 200, 192],
       [ 25,  91, 230, 242,  14, 110,  81,  60],
       [532,   0, 144,  70, 165,  21,   6, 342]])

In [68]:
np.divide(g,e)

array([[ 0.11538462,  0.        ,  0.57894737,  1.14285714,  0.28947368,
         3.        ,  1.71428571,  0.55555556],
       [ 0.27586207,  0.46153846,  0.20689655,  0.21428571,  0.24      ,
         2.33333333,  0.9       ,  1.36363636],
       [ 0.37837838,  0.92307692,  0.13793103,  0.2       ,  1.27272727,
         0.71428571,  0.125     ,  1.2       ],
       [ 0.4       ,  0.02564103, 15.        ,  1.25      ,  0.        ,
         0.15384615,  0.52173913,  0.8       ],
       [ 0.10526316,  0.3125    ,  0.26666667,  0.27272727,  0.28205128,
         0.03448276,  0.27272727,  1.42857143],
       [ 4.5       ,  0.68181818,  1.        ,  1.28571429,  2.        ,
         0.65217391,  0.5       ,  0.33333333],
       [ 1.        ,  0.53846154,  0.43478261,  0.5       ,  3.5       ,
         0.22727273,  1.        ,  1.66666667],
       [ 0.36842105,  0.        ,  0.5625    ,  0.7       ,  1.36363636,
         2.33333333,  0.16666667,  0.23684211]])

In [69]:
np.mean(g, axis=0)

array([ 8.375,  6.5  ,  9.75 ,  7.125,  9.75 ,  8.   ,  7.5  , 10.375])

In [70]:
np.mean(g)

8.421875

In [71]:
np.mean(g,axis=1)

array([ 7.875,  9.5  ,  9.375,  8.875,  5.5  , 10.5  ,  8.   ,  7.75 ])

In [73]:
g.max(axis=0)

array([14, 15, 30, 11, 15, 15, 12, 15])

In [74]:
g.max(axis=1)

array([15, 15, 15, 30, 11, 15, 11, 15])

In [75]:
g.max()

30

In [76]:
g.sum()

539

In [77]:
g.sum(axis=0)

array([67, 52, 78, 57, 78, 64, 60, 83])